### ISSUE TITLE
bind to super

### ISSUE THREAD

**Issue by edudebortoli** [icedman/search-light#23]
I`m tryin to bind the menu to my superkey (just the super).
My question, theres a way to call it by the cli or to address the search-light to only superkey on its own configuration? Im tryin to use [super-key](https://extensions.gnome.org//extension/5188/super-key/) to change the default behaviour.

**Comment by icedman** [comment]
This is probably possible. We can override the overview with something like:

```Main.overview.toggle = () => { Main._searchLight.show() }```

But I'll look for a cleaner way (without disabling the overview entirely)

**Comment by pathmann** [comment]
I've bound search light to the super key (only) by using dconf-editor to bind the overview (org.gnome.mutter overlay-key) to 'Menu' and then set shortcut-search of search-light to 'Super_L'.

**Comment by dyskette** [comment]
A side effect of using Super_L is that every time you use a shortcut that involves Super key then Search Light shows up until you press the second key of the shortcut. And it captures the input of the keyboard. 🤣 

Try it with Super + Tab.

My guess is currently it's using KeyDown instead of KeyUp, maybe?
