### ISSUE TITLE
UX/UI Can't modify keyboard shortcut. Bright background uses bright text.

### ISSUE THREAD

**Issue by martinlindelof** [icedman/search-light#3]
UX Probably not an issue, and being worked on but no ability to change keyboard shortcut.
UI Changing background color to White/Bright has White/Bright text, probably should automagically make text dark on bright backgrounds. Looks great otherwise! will keep an eye on this extension.

**Comment by MuhametSmaili** [comment]
The keyboard shortcut should be a `priority` in my opinion, because it is hard to use otherwise.

**Comment by icedman** [comment]
Text now adapts to background. Black for dark background, White for light;
It won't be perfect in some instances;

Keyboard shortcut setting - not yet added

**Comment by icedman** [comment]
Checkout release 3. These have been addressed.

**Comment by MuhametSmaili** [comment]
@icedman now i installed the extension. Yes, the shortcut works. I just removed my launcher and will try to use just your extension. until now it is awesome.
GREAT JOB.
Also Kudos to you, for addressing the multi-monitor issue. 
I think this issue is addressed and resolved, so this issue can be closed.
