### ISSUE TITLE
Can't bind to super + key

### ISSUE THREAD

**Issue by Yasso9** [icedman/search-light#54]
Hi,

I want to bind the extension to super + key. For example, if I want to bind to super + space or super + v it doesn't work.
Also, it would be cool to quit the search by pressing esc.

Apart from that, it's a great extension ! Thanks

**Comment by Yasso9** [comment]
Tell me if it's a duplicate of : https://github.com/icedman/search-light/issues/50
The difference is he have the issue just because he wants to bind super key alone and my issue is for super + key.

**Comment by pathmann** [comment]
That works for me for some  keys (but not all), but you have to remove the default key binding of Super_L to gnomes application overview first.

I guess some key combinations won't work, because they are already bound to other parts of gnome (for example Super_L + m  for the clock/notifcation/calendar panel). These bindings might be removable too and then it could work.

**Comment by Yasso9** [comment]
Thanks a lot, it works !!
I wanted to use super + space, and I haven't noticed that the same shortcut was attached to 'switch to next input source'. Also, I still have the key binding of Super-L to app overview.
