### ISSUE TITLE
Extension changed my theme

### ISSUE THREAD

**Issue by matteocavestri** [icedman/search-light#59]
After I installed this extension, my main gnome search changed theme (also volume scrolls, keyboard backlight stroll...). I have removed this extension and the problem persists. Can anyone help me? I like the default adwaita theme.

**Comment by matteocavestri** [comment]
It also changed the close icon (the little x in the top right angle of a window) during the activity view

**Comment by Hyperspeed1313** [comment]
Are you sure this was caused by the Search Light extension? This extension is fairly simple and shouldn't be affecting those portions of the system. Are you able to reproduce this on a clean install, having installed no other extensions installed?

Are you using a distro that ships modifications to the Adwaita theme out of the box (i.e. Ubuntu)?

**Comment by Hyperspeed1313** [comment]
Having also spun up an Ubuntu 23.04 VM I was unable to reproduce your problem there either.

**Comment by matteocavestri** [comment]
It wasn't that extension (it was related tu just-perfection), sorry for the issue, I'll close it
